# Generated by Django 5.0.6 on 2024-07-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takes', '0002_remove_take_dislikes_remove_take_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
